/*
~~HTML
  1. Structure: Sets up the layout.
  2. Content: Adds text, images, links.
  3. Tags: Uses elements like <p>, <a>.
  4. Hierarchy: Organizes elements in a tree.

~~CSS
  1. Style: Sets the look and feel.
  2. Colors & Fonts: Customizes text and background.
  3. Layout: Controls position and size.
  4. Selectors: Targets specific HTML elements.  

~~JS
  1. JavaScript has nothing to do with Java
  2. Actions: Enables interactivity.
  3. Updates: Alters page without reloading.
  4. Events: Responds to user actions.
  5. Data: Fetches and sends info to server.  

  1. JavaScript runs at the client side in the browser.
  2. Coffee Script / TypeScript are transpiled to JavaScript.
*/