/*
A STRING CAN BE REPRESENTED AS A POINTER TO ITS FIRST CHARACTER.FOR EXAMPLE,char *str = MEET; MAKES STR A POINTER TO THE FIRST CHARACTER OF THE STRING LITERAL "MEET"(IN SIMPLE WORDS,THERE ARE TWO WAYS TO DECLARE A STRING).
*/

/*
1.IMMUTABLE STRING LITERALS: STRING LITERALS ASSIGNED TO CHARACTER POINTERS ARE STORED IN READ-ONLY MEMORY,MAKING THEM IMMUTABLE.ATTEMPTING TO MODIFY THEM,e.g.,M[0] = 'k'; ,LEADS TO UNDEFINED BEHAVIOUR.

2.ARRAY vs. POINTER: WHILE AN ARRAY NAME IS A CONSTANT POINTER TO ITS FIRST ELEMENT ,A CHARACTER ARRAY ALLOWS MODIFICATION OF ITS ELEMENTS.
*/
#include <stdio.h>
int main()
{
  // CHARACTER ARRAY ~ MODIFIABLE
  char M[] = "MEET";
  M[0] = 'm'; // MODIFYING THE FIRST CHARACTER
  printf("MODIFIED ARRAY STRING: %s\n", M);

  // CHARACTER POINTER TO A STRING LITERAL ~ NOT MODIFIABLE
  char *M = "MEET";//ASK RISHAB SIR
  // ATTEMPTING TO MODIFY THE FIRST CHARACTER
  M[0] = 'K'; // THIS WILL LEAD TO UNDEFINED BEHAVIOUR
  printf("POINTER STRING(ATTEMPTED MODIFICATION): %s\n", M);
  return 0;
}