/*
A.WHAT IS A STRING?

1.CHARACTER ARRAY: A STRING IS A SEQUENCE OF CHARACTERS TERMINATED BY A NULL CHARACTER('\0').
2.NULL TERMINATION: THE NULL CHARACTER('\0') MARKS THE END OF THE STRING ,NOT INCLUDED IN ITS LENGTH.3.STRING LITERALS: DEFINED IN DOUBLE QUOTES,e.g.,"hello world".
4.MUTABLE: STRINGS CAN BE MODIFIED WHEN STORED IN A CHARACTER ARRAY.


B.STRING MEMORY ALLOCATION

1.MEMORY ALLOCATION: FIXED SIZE AT COMPILE TIME,INCLUDING THE NULL TERMINATOR.
2.CONTIGUOS MEMORY: STRINGS ARE STORED CONTIGUOUSLY LIKE ARRAYS.


C.STRING INITIALIZATION 

THERE ARE FOUR WAYS TO INITIALIZE:
1.char c[] = "abcd";OR,
2.char c[50] = "abcd";OR,
3.char c[] = {'a','b','c','d','\0'};OR,
4.char c[5] = {'a','b','c','d','\0'};

[a][b][c][d][[\0]


D.FORMAT SPECIFIERS

1.OUTPUT: %s IS USED WITH printf TO OUTPUT A STRING.
2.INPUT: %s IS USED WITH scanf TO READ A STRING INTO A CHARACTER ARRAY.IT STOPS READING UPON ENCOUNTERING WHITESPACE,A NEWLINE,OR EOF.
3.NO & WITH scanf: UNLIKE OTHER DATA TYPES ,WHEN USING %s WITH scanf ,YOU DON'T PREFIX THE VARIABLE NAME WITH & BCOZ A STRING NAME ACTS AS A POINTER.
4.SAFETY: TO PREVENT BUFFER OVERFLOW WITH scanf, SPECIFY A MAXIMUM FIELD WIDTH,e.g.,%9s FOR A CHAR ARRAY OF SIZE 10.

*/
#include <stdio.h>
int main()
{ // WAYS TO INITIALIZE A STRING
  //  char c[] = "MEET";
  //  char c[50] = "abcd";
  //  char c[] = {'a', 'b', 'c', 'd', '\0'};
  //  char c[5] = {'a', 'b', 'c', 'd', '\0'};

  char M[5]; // ALLOCATE A CHARACTER ARRAY

  printf("ENTER YOUR NAME: "); // READ A STRING WITH A SAFETY LIMIT

  scanf(" %4s", M);//after whitespace ,scanf will not read your string,it will ignore the rest.
  // OUTPUT THE ENTERED STRING
  printf("GOOD MORNING %s", M);

  return 0;
}
