/*
~~MULTI-DIMENSIONAL ARRY

  1.GENERALIZATION: EXTEND TWO-DIMENSIONAL ARRAYS TO MORE DIMENSIONS,LIKE 3D FOR CUBES OR HIGHER.
  2.DECLARATION: SPECIFY EACH DIMENSION,e.g., int arr[2][3][4] FOR A 3D ARRAY.
  3.INITIALIZATION: NESTED BRACES FOR DIMENSIONS,e.g., int arr[2][2][2] = {
  {{1,2},{3,4}},
  {{5,6},{7,8}}
  };.
  4.ELEMENT ACCESS: USE INDICES FOR EACH DIMENSION,e.g., arr[1][0][1] FOR A 3D ARRAY ELEMENT.
  5.ROW-MAJOR ORDER: MEMORY LAYOUT CONTINUES WITH ELEMENTS STORED IN CONTINUOS LOCATIONS,DIMENSION BY DIMENSION.

*/
