/* 
~~POINTER ARITHMETIC 
*(arr + i) = EQUALS arr[i]
 
 1.MEMORY INCREMENT/DECREMENT: ptr++ OR ptr-- MOVES THE POINTER TO THE NEXT OR PREVIOUS MEMORY LOCATION BASED ON THE TYPE'S SIZE.(2 BYTE HAI SIZE TO 2 MOVE KAREGA....)
 2.ADDTION/SUBTRACTION: ADDING OR SUBTRACTING AN INTEGER N FROM A POINTER MOVES IT N ELEMENTS FORWARD OR BACKWARD.
 3.DIFFERENCE: SUBTRACTING ONE POINTER FROM ANOTHER GIVES THE NUMBER OF ELEMENTS BETWEEN THEM.
 
*/