/* Q1.*/
console.log(`YOUR FINAL BILL AMOUNT IS₹ ${1 * 100 + 2 * 10 + 1 * 30}`);
console.log();

/*Q2.*/
console.log(`YOUR GST TAX AMOUNT IS ₹ ${((1 * 79990 + 2 * 24990) * 18) / 100}`);
console.log();

/*Q3.*/
console.log(`MEET`);
console.log('ANURAG');
console.log("YUG");
console.log();

/*Q4.*/
console.log("MEET'S FAV NUMBER IS"+" " + 5);
console.log("FRIENDS"+" "+ "FOREVER");
console.log();

/*Q5.*/
console.log(`YOUR FINAL MYNTRA BAG AMOUNT IS ₹18003.8618`);
