/*
~~STRINGS
  1. Strings hold textual data, anything from a single character to paragraph.
  2. Strings can be defined using single quotes ' ', double quotes " ", or backticks ` `. Backticks allow for template literals, which can include variables.
  3. You can combine (concatenate) strings using the + operator. For example, "Hello" + " World" will produce "Hello World".
  4.'You have got' + (1 + 1 + 1) + 'votes' = 'YOU HAVE GOT 3 VOTES'.
*/