// //FOR IN
// let BILLIONARE = {
//   Name: "MEET PARSANA",
//   Age: 18,
//   Annual_Income: 33000000000000000,
// };

// console.log();
// for (let key in BILLIONARE) {
//   console.log(key + ": " + BILLIONARE[key]);
// }
// console.log();

// let MILLIONARE = {
//   Name: "MEETUDO",
//   Age: 19,
//   NumberOfCars_owned: 15,
// };

// console.log();
// for (let gand in MILLIONARE) {
//   console.log(gand + ":" + MILLIONARE[gand]);
// }
// console.log();

// //FOR OF
// let CHANKYA = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10];
// for (let LAND in CHANKYA) {
//   console.log(LAND);
// }



// let GAND = [1, 2, 3, 4, 5, 6, 7, 8, 9];

// function ArrayLargest(GAND){
// let MAX = 0;
// for (let i = 0; i < 15; i++) {
//   if (MAX < GAND[i]) {
//     MAX = GAND[i];
//   }
// }
// return MAX;
// }

console.log(ArrayLargest(GAND));

let RAND = new Object();
RAND.Color = "PINK";
RAND.Age = 26;
RAND.Favoutite_MAN = "KUSHAL";

console.log(RAND.Favoutite_MAN);



